name: ci-cd
run-name: Linting and Deploying
on:
  push:
    branches:
      - "main"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: CI
        uses: ./.github/workflows/ci.yaml

  Deploy:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Deploy
        uses: ./.github/workflows/github-pages.yaml
